---
  - hosts: all
    remote_user: ec2-user
    become: true
    gather_facts: no
    ignore_errors: true 
    tasks: 
        - name: Install apache
          yum: name=httpd state=present
          notify: restart apache
        - name: Copy file with owner & permissions
          copy:
            src: /data/other-files/index.html
            dest: /var/www/html/index.html
            owner: root
            group: root
            mode: '0777'
    handlers:
        - name: restart apache
          service: name=httpd state=restarted